"""create first2

Revision ID: 58bf7df9e1c7
Revises: 1e9990829125
Create Date: 2024-06-09 17:17:16.504607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bf7df9e1c7'
down_revision: Union[str, None] = '1e9990829125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_vehicle_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'vehicle_id')
    op.add_column('vehicles', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'user_id')
    op.add_column('users', sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_vehicle_id_fkey', 'users', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###
